#!/bin/bash

# Filename of the script that user want to run
filename=$1;

# Current working directory of user
cwd=$(pwd);

# Absolute path to the script that user want to run
abs_path=$cwd/$filename;

# Compiling user's script into temp directory using the Rust compiler,
# running compiled binary and removing it from temp.
rustc -o /tmp/rspy.out $abs_path; /tmp/rspy.out 2>/dev/null; rm /tmp/rspy.out 2>/dev/null

